version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install dependencies
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             sudo apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev libmysqlclient-dev libpq-dev unixodbc-dev freetds-bin unixodbc-dev tdsodbc --yes
             python3 -m pip install -U pip 
             python3 setup.py install 
             pip3 install -r requirements.txt
             pip3 install -r requirements-dev.txt
             pip3 install -r requirements-extra.txt
             nosetests --stop -v --cover-package=flask_appbuilder flask_appbuilder.tests --ignore-files="test_mongoengine\.py"
 
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
